// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace SAL_VM.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SAL_VM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Arrow_Right
        {
            get
            {
                var obj = ResourceManager.GetObject("Arrow_Right", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Complier_RUN
        {
            get
            {
                var obj = ResourceManager.GetObject("Complier_RUN", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Console_A
        {
            get
            {
                var obj = ResourceManager.GetObject("Console_A", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Dell_UltraSharp_27
        {
            get
            {
                var obj = ResourceManager.GetObject("Dell_UltraSharp_27", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap EYE_BLUE_
        {
            get
            {
                var obj = ResourceManager.GetObject("EYE_BLUE_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Icon_UpVote
        {
            get
            {
                var obj = ResourceManager.GetObject("Icon_UpVote", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ipad_mockup_hands
        {
            get
            {
                var obj = ResourceManager.GetObject("ipad_mockup_hands", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The section numbers are per the Berkeley Logo Reference Manual in Brian Harvey&apos;s Computer Science Logo Style volume 2: Advanced Techniques for ease of comparison.
        /// 
        /// Data Types and Syntax
        /// Data Structure Primitives
        /// Communication
        /// Arithmetic
        /// Logical Operations
        /// Graphics
        /// Workspace Management
        /// Control Structures
        /// Data Types and Syntax
        /// &quot;word
        /// &apos;word
        /// number
        /// Word. (Quoted words are terminated by [](){} or whitespace, \ to escape.)
        /// show &quot;hello
        /// show &quot;hello\ logo
        /// show 12.34
        /// :variable
        /// Input definition/varia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LOGO_QUICK_REF
        {
            get
            {
                return ResourceManager.GetString("LOGO_QUICK_REF", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to SpydazWeb Assembly Language : 
        /// 	Description :
        /// 		This assembly language is specific to this virtual processor 
        /// 		Enableing for the code to be executed on the cpu: 
        /// 		This is a Micro based instruction set (Misc)
        /// 	ZX81:
        /// 		_PUSH					: Pushes items on to the stack (top)
        /// 		_POP					: Pops items off the stack (top)
        /// 		_PEEK					: Views items on the stack (top)
        /// 		_WAIT					: Pauses execution of code
        /// 		_PAUSE					: Pauses execution of code
        /// 		_HALT					: HALT execution of code
        /// 		_RESUME					: Resumes execu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuickRef_SAL
        {
            get
            {
                return ResourceManager.GetString("QuickRef_SAL", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Script
        {
            get
            {
                var obj = ResourceManager.GetObject("Script", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SERIES_1_sal9000
        {
            get
            {
                var obj = ResourceManager.GetObject("SERIES_1_sal9000", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap up
        {
            get
            {
                var obj = ResourceManager.GetObject("up", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap X_SERIES_AL_9000s
        {
            get
            {
                var obj = ResourceManager.GetObject("X_SERIES_AL_9000s", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}