'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AI_BASIC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Complier_RUN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Complier_RUN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Console_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Console_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property console_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("console_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dell_UltraSharp_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dell_UltraSharp_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EYE_BLUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EYE_BLUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_UpVote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_UpVote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The section numbers are per the Berkeley Logo Reference Manual in Brian Harvey&apos;s Computer Science Logo Style volume 2: Advanced Techniques for ease of comparison.
        '''
        '''Data Types and Syntax
        '''Data Structure Primitives
        '''Communication
        '''Arithmetic
        '''Logical Operations
        '''Graphics
        '''Workspace Management
        '''Control Structures
        '''Data Types and Syntax
        '''&quot;word
        '''&apos;word
        '''number
        '''Word. (Quoted words are terminated by [](){} or whitespace, \ to escape.)
        '''show &quot;hello
        '''show &quot;hello\ logo
        '''show 12.34
        ''':variable
        '''Input definition/varia [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LOGO_REF() As String
            Get
                Return ResourceManager.GetString("LOGO_REF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SpydazWeb Assembly Language : 
        '''	Description :
        '''		This assembly language is specific to this virtual processor 
        '''		Enableing for the code to be executed on the cpu: 
        '''		This is a Micro based instruction set (Misc)
        '''	ZX81:
        '''		_PUSH					: Pushes items on to the stack (top)
        '''		_POP					: Pops items off the stack (top)
        '''		_PEEK					: Views items on the stack (top)
        '''		_WAIT					: Pauses execution of code
        '''		_PAUSE					: Pauses execution of code
        '''		_HALT					: HALT execution of code
        '''		_RESUME					: Resumes execu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SAL_REF() As String
            Get
                Return ResourceManager.GetString("SAL_REF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Script() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Script", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SERIES_1_sal9000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SERIES_1_sal9000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Turtle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Turtle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TurtleGraphics.NET - Developer&apos;s Reference
        '''
        '''The interface is intentionally simplified through a single static class (I know this is not a good practice in OOP), to enable kids start playing with the turtle with just few clicks, without knowing anything about &quot;classes&quot; and &quot;objects&quot;. The class Turtle supports all major turtle graphics primitives in Windows Forms C# / .NET GUI applications:
        '''•Init() - initializes the turtle graphics system. Callers can specify the target Windows Forms control to hold the dr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TurtleREF() As String
            Get
                Return ResourceManager.GetString("TurtleREF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;    Z-80 CPU Instruction Set
        '''    &apos;---- --- ----------- ---
        '''
        '''    &apos;&apos;ADC   HL, ss      Add With carry register pair ss To HL.
        '''    &apos;&apos;ADC   A, s        Add With carry operand s To accumulator.
        '''    &apos;&apos;ADD   A, n        Add value n To accumulator.
        '''    &apos;&apos;ADD   A, r        Add register r To accumulator.
        '''    &apos;&apos;ADD   A,(HL)      Add location (HL) To acccumulator.
        '''    &apos;&apos;ADD   A,(IX + d)  Add location (IX+d) To accumulator.
        '''    &apos;&apos;ADD   A,(IY + d)  Add location (IY+d) To accumulator.
        '''    &apos;&apos;ADD   HL, ss      Add [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Zx80Ref() As String
            Get
                Return ResourceManager.GetString("Zx80Ref", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
